// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activation = "passive" | { "toggle": { default_on: boolean, } } | "activated" | "reaction";
