// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmorKind } from "./ArmorKind";

export type ArmorItem = { name: string, base_ac: number, kind: ArmorKind, 
/**
 * Max DEX bonus allowed: `None` = light (full DEX), `Some(2)` = medium,
 * `Some(0)` = heavy.
 */
dex_cap?: number | null, };
