// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

export type BackgroundSummary = { id: string, name: string, abilities: Array<Ability>, };
