// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContribOp } from "./ContribOp";

/**
 * One line of a stat's breakdown.
 */
export type BreakdownLine = { source: string, op: ContribOp, band: string, value: number, note: string | null, 
/**
 * False when this line was dropped (e.g. lost the Base max, or a non-stacking dupe).
 */
applied: boolean, };
