// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A spellcasting source id (usually a class id), e.g. `"wizard"`.
 */
export type CastingSource = string;
