// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { ClassEntry } from "./ClassEntry";
import type { DeathSaves } from "./DeathSaves";
import type { Equipment } from "./Equipment";
import type { HpState } from "./HpState";
import type { Meta } from "./Meta";
import type { RecordedChoice } from "./RecordedChoice";
import type { ResourceId } from "./ResourceId";
import type { WeaponInstance } from "./WeaponInstance";

export type CharacterSheet = { meta: Meta, 
/**
 * Base ability scores, before any modifiers from species/background/feats.
 */
abilities: { [key in Ability]?: number }, species?: string | null, background?: string | null, classes: Array<ClassEntry>, feats: Array<string>, choices: Array<RecordedChoice>, hp: HpState, 
/**
 * Current value of each resource pool (max is computed).
 */
resources: { [key in ResourceId]: number }, 
/**
 * Spell slots expended, by slot level (max is computed).
 */
slots_expended: { [key in number]: number }, 
/**
 * Hit dice spent, by die size.
 */
hit_dice_spent: { [key in number]: number }, conditions: Array<string>, exhaustion: number, 
/**
 * Toggles / active effects currently on (matched by `Condition::EffectActive`).
 */
active_effects: Array<string>, equipment: Equipment, weapons: Array<WeaponInstance>, 
/**
 * Spell ids the character knows (for Known-caster classes like Sorcerer/Bard).
 */
known_spells: Array<string>, 
/**
 * Spell ids the character has prepared (for Prepared-caster classes like Cleric/Wizard).
 */
prepared_spells: Array<string>, 
/**
 * The spell currently being concentrated on, if any.
 */
concentration?: string | null, death_saves: DeathSaves, inspiration: boolean, 
/**
 * Free-form player notes (markdown/plain text).
 */
notes: string, };
