// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOptions } from "./ChoiceOptions";

/**
 * A decision the player must make (skill picks, fighting style, ASI, subclass…).
 */
export type ChoicePoint = { 
/**
 * Globally unique key; a [`RecordedChoice`](crate::sheet::RecordedChoice)
 * with the same key resolves it.
 */
id: string, prompt: string, choose: number, options: ChoiceOptions, };
