// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { NamedOption } from "./NamedOption";
import type { Skill } from "./Skill";

export type ChoiceOptions = { "kind": "skills", from: Array<Skill>, } | { "kind": "expertise", from: Array<Skill>, } | { "kind": "feat", category?: string | null, } | { "kind": "ability-score-increase" } | { "kind": "ability-scores", from: Array<Ability>, points: number, max_each: number, } | { "kind": "subclass" } | { "kind": "spells", from: Array<string>, max_level?: number | null, } | { "kind": "weapon-mastery", from: Array<string>, } | { "kind": "named", from: Array<NamedOption>, };
