// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassSummary = { id: string, name: string, hit_die: number, 
/**
 * "full" | "half" | "third" | "pact" | "none" — caster progression, if any.
 */
caster: string | null, subclass_level: number, };
