// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbilityView } from "./AbilityView";
import type { EffectView } from "./EffectView";
import type { EvalError } from "./EvalError";
import type { HitDiePool } from "./HitDiePool";
import type { PassiveView } from "./PassiveView";
import type { PendingChoice } from "./PendingChoice";
import type { ResolvedFeature } from "./ResolvedFeature";
import type { ResourceView } from "./ResourceView";
import type { SaveView } from "./SaveView";
import type { SkillView } from "./SkillView";
import type { SpeedView } from "./SpeedView";
import type { SpellSlotView } from "./SpellSlotView";
import type { SpellcastingView } from "./SpellcastingView";
import type { StatBreakdown } from "./StatBreakdown";
import type { WeaponView } from "./WeaponView";

export type ComputedCharacter = { name: string, level: number, proficiency_bonus: number, max_hp: StatBreakdown, current_hp: number, temp_hp: number, armor_class: StatBreakdown, initiative: StatBreakdown, speeds: Array<SpeedView>, abilities: Array<AbilityView>, saves: Array<SaveView>, skills: Array<SkillView>, passives: Array<PassiveView>, resources: Array<ResourceView>, spell_slots: Array<SpellSlotView>, spellcasting: Array<SpellcastingView>, weapons: Array<WeaponView>, masteries_known: number, effects: Array<EffectView>, concentration: string | null, hit_dice: Array<HitDiePool>, features: Array<ResolvedFeature>, pending_choices: Array<PendingChoice>, carrying_capacity: number, errors: Array<EvalError>, };
