// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gate for whether a contribution is currently active.
 */
export type Condition = { "if": "always" } | { "if": "effect-active", id: string, } | { "if": "wearing-armor" } | { "if": "unarmored" } | { "if": "wielding-shield" };
