// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a contribution combines into its target stat. Applied in band order:
 * Base → Add → Multiply → Floor → Cap → Override.
 */
export type ContribOp = "base" | "add" | "multiply" | "floor" | "cap" | "override";
