// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { ContribOp } from "./ContribOp";
import type { D20Effect } from "./D20Effect";
import type { StatId } from "./StatId";
import type { ValueExpr } from "./ValueExpr";

/**
 * One traceable input to a stat.
 */
export type Contribution = { target: StatId, op: ContribOp, value: ValueExpr, when?: Condition | null, effect?: D20Effect | null, note?: string | null, 
/**
 * Contributions sharing a non-`None` group don't stack — only the largest applies.
 */
stack_group?: string | null, };
