// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceNote } from "./SourceNote";

export type D20Channel = { advantage: Array<SourceNote>, disadvantage: Array<SourceNote>, auto_fail: Array<SourceNote>, auto_success: Array<SourceNote>, };
