// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-numeric effects on a d20 test. Per 2024, one advantage cancels any number
 * of disadvantages and vice versa — they do not stack.
 */
export type D20Effect = "advantage" | "disadvantage" | "auto-fail" | "auto-success";
