// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvState } from "./AdvState";
import type { AutoOutcome } from "./AutoOutcome";
import type { D20Channel } from "./D20Channel";
import type { StatBreakdown } from "./StatBreakdown";

/**
 * The resolved result of a d20 test: the numeric bonus + its breakdown, the
 * advantage state, and any auto outcome.
 */
export type D20Test = { total: number, breakdown: StatBreakdown, adv: AdvState, channel: D20Channel, auto: AutoOutcome, };
