// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dice expression like `2d6`.
 */
export type Dice = { count: number, sides: number, };
