// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArmorItem } from "./ArmorItem";

export type Equipment = { armor?: ArmorItem | null, shield: boolean, };
