// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalErrorKind } from "./EvalErrorKind";
import type { StatId } from "./StatId";

export type EvalError = { stat: StatId, kind: EvalErrorKind, };
