// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activation } from "./Activation";
import type { ChoicePoint } from "./ChoicePoint";
import type { Contribution } from "./Contribution";
import type { ProficiencyGrant } from "./ProficiencyGrant";
import type { ResourceDef } from "./ResourceDef";
import type { SpellGrant } from "./SpellGrant";

/**
 * The universal effect bundle.
 */
export type Feature = { id: string, name: string, description: string, 
/**
 * Optional tag for feat filtering in choices, e.g. `"origin"`,
 * `"fighting-style"`, `"epic-boon"`. Ignored by the math.
 */
category?: string | null, activation: Activation, contributions: Array<Contribution>, proficiencies: Array<ProficiencyGrant>, resources: Array<ResourceDef>, spell_grants: Array<SpellGrant>, choices: Array<ChoicePoint>, };
