// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pool of hit dice of one size (multiclass characters have several).
 */
export type HitDiePool = { sides: number, total: number, spent: number, };
