// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HpState = { current: number, temp: number, 
/**
 * Optional per-level HP rolls; when empty, the engine uses fixed averages.
 */
rolled: Array<number>, };
