// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contribution } from "./Contribution";
import type { ProficiencyGrant } from "./ProficiencyGrant";

export type NamedOption = { id: string, name: string, contributions: Array<Contribution>, proficiencies: Array<ProficiencyGrant>, };
