// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCategory } from "./NoteCategory";

/**
 * A single player note card (backstory, quest log, NPC, etc.).
 */
export type Note = { id: string, title: string, content: string, category: NoteCategory, pinned: boolean, 
/**
 * ISO-8601 timestamps, set by the frontend (the engine stays time-free).
 */
created_at: string, updated_at: string, };
