// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Skill } from "./Skill";

export type PassiveView = { skill: Skill, value: number, };
