// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOptions } from "./ChoiceOptions";

/**
 * An unresolved decision the player still has to make.
 */
export type PendingChoice = { key: string, prompt: string, choose: number, options: ChoiceOptions, source: string, };
