// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { Skill } from "./Skill";

export type ProficiencyGrant = { "kind": "skill", skill: Skill, expertise: boolean, } | { "kind": "saving-throw", ability: Ability, } | { "kind": "tool", tool: string, } | { "kind": "weapon", weapon: string, } | { "kind": "armor", armor: string, } | { "kind": "language", language: string, };
