// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved [`ChoicePoint`](crate::feature::ChoicePoint): `key` matches the
 * choice's id, `picks` are the selected option ids / values.
 */
export type RecordedChoice = { key: string, picks: Array<string>, };
