// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Recharge } from "./Recharge";
import type { ResourceId } from "./ResourceId";
import type { ResourceKind } from "./ResourceKind";

export type ResourceView = { id: ResourceId, name: string, kind: ResourceKind, current: number, max: number, die: number | null, recharge: Recharge, };
