// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource pool id, e.g. `"superiority-dice"`. Content-driven.
 */
export type ResourceId = string;
