// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Recharge } from "./Recharge";
import type { ResourceId } from "./ResourceId";
import type { ResourceKind } from "./ResourceKind";
import type { ValueExpr } from "./ValueExpr";

export type ResourceDef = { id: ResourceId, name: string, kind: ResourceKind, 
/**
 * Base die size for `Dice` pools (e.g. 8 for a d8).
 */
die?: number | null, 
/**
 * Die size by character level (largest key `<= level` applies).
 */
die_scaling?: { [key in number]: number } | null, 
/**
 * Maximum size of the pool — a traceable expression.
 */
max: ValueExpr, recharge: Recharge, };
