// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A feature the character has, for display.
 */
export type ResolvedFeature = { name: string, description: string, source: string, kind: string, };
