// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { D20Test } from "./D20Test";

export type SaveView = { ability: Ability, proficient: boolean, test: D20Test, };
