// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { D20Test } from "./D20Test";
import type { Skill } from "./Skill";

export type SkillView = { skill: Skill, ability: Ability, proficient: boolean, expertise: boolean, bonus: number, test: D20Test, };
