// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovementKind } from "./MovementKind";

export type SpeedView = { kind: MovementKind, value: number, };
