// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

/**
 * The saving throw a spell forces and the effect on a success.
 */
export type SpellSave = { 
/**
 * The ability the TARGET uses for its saving throw.
 */
ability: Ability, 
/**
 * What happens on a successful save, e.g. `"half damage on a success"`.
 */
effect: string, };
