// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";

export type SpellcastingView = { source: string, ability: Ability, save_dc: number, attack_bonus: number, prepared: number | null, };
