// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a spell's attack is melee or ranged.
 */
export type SpellAttack = "melee" | "ranged";
