// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The material, verbal, and somatic components of a spell.
 */
export type SpellComponents = { verbal: boolean, somatic: boolean, 
/**
 * Specific material component required (omit if none).
 */
material?: string | null, };
