// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Damage a spell deals on a hit or failed save.
 */
export type SpellDamage = { 
/**
 * Dice expression, e.g. `"1d10"`, `"3d6"`, `"3 × 1d4+1"`.
 */
dice: string, 
/**
 * Damage type, e.g. `"fire"`, `"cold"`, `"healing"`.
 */
damage_type: string, };
