// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellAttack } from "./SpellAttack";
import type { SpellComponents } from "./SpellComponents";
import type { SpellDamage } from "./SpellDamage";
import type { SpellSave } from "./SpellSave";
import type { SpellSchool } from "./SpellSchool";

/**
 * A single spell definition, as authored in `content/spells/*.json`.
 */
export type SpellDef = { 
/**
 * Kebab-case unique identifier, e.g. `"fire-bolt"`.
 */
id: string, name: string, 
/**
 * Spell level; 0 = cantrip.
 */
level: number, school: SpellSchool, 
/**
 * Class ids that have this spell on their spell list, e.g. `["wizard", "sorcerer"]`.
 */
classes: Array<string>, 
/**
 * Casting time description, e.g. `"1 action"`.
 */
casting_time: string, 
/**
 * Range description, e.g. `"120 feet"`.
 */
range: string, components: SpellComponents, 
/**
 * Duration description, e.g. `"Instantaneous"`.
 */
duration: string, 
/**
 * Whether the spell requires concentration.
 */
concentration: boolean, 
/**
 * Whether the spell can be cast as a ritual.
 */
ritual: boolean, 
/**
 * Rules text for the spell (1–3 sentences for the proof set).
 */
description: string, 
/**
 * Whether the spell requires a spell attack roll, and if so whether melee or ranged.
 */
attack?: SpellAttack | null, 
/**
 * Saving throw the target must make (if any).
 */
save?: SpellSave | null, 
/**
 * Damage (or healing) the spell deals.
 */
damage?: SpellDamage | null, };
