// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakdownLine } from "./BreakdownLine";
import type { StatId } from "./StatId";

/**
 * The full provenance of a single stat.
 */
export type StatBreakdown = { stat: StatId, label: string, total: number, lines: Array<BreakdownLine>, };
