// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { CastingSource } from "./CastingSource";
import type { ClassId } from "./ClassId";
import type { MovementKind } from "./MovementKind";
import type { ResourceId } from "./ResourceId";
import type { Skill } from "./Skill";
import type { SlotLevel } from "./SlotLevel";
import type { WeaponKind } from "./WeaponKind";

/**
 * Every computable value in the character. The evaluator must handle each
 * variant, so adding a stat is a compiler-guided checklist.
 */
export type StatId = { "kind": "character-level" } | { "kind": "class-level", "of": ClassId } | { "kind": "ability-score", "of": Ability } | { "kind": "ability-modifier", "of": Ability } | { "kind": "proficiency-bonus" } | { "kind": "max-hit-points" } | { "kind": "armor-class" } | { "kind": "initiative" } | { "kind": "speed", "of": MovementKind } | { "kind": "saving-throw", "of": Ability } | { "kind": "skill-bonus", "of": Skill } | { "kind": "passive-score", "of": Skill } | { "kind": "spell-save-dc", "of": CastingSource } | { "kind": "spell-attack-bonus", "of": CastingSource } | { "kind": "resource-max", "of": ResourceId } | { "kind": "spell-slot-max", "of": SlotLevel } | { "kind": "attacks-per-action" } | { "kind": "weapon-attack-bonus", "of": WeaponKind } | { "kind": "weapon-damage-bonus", "of": WeaponKind } | { "kind": "weapon-masteries-known" } | { "kind": "carrying-capacity" } | { "kind": "custom", "of": string };
