// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { Dice } from "./Dice";
import type { StatId } from "./StatId";

export type ValueExpr = { "expr": "literal", value: number, } | { "expr": "stat", id: StatId, } | { "expr": "ability-mod", ability: Ability, } | { "expr": "sum", terms: Array<ValueExpr>, } | { "expr": "product", terms: Array<ValueExpr>, } | { "expr": "min", terms: Array<ValueExpr>, } | { "expr": "max", terms: Array<ValueExpr>, } | { "expr": "scaled", per: ValueExpr, by: ValueExpr, } | { "expr": "level-table", on: ValueExpr, table: Array<[number, number]>, } | { "expr": "floor-div", num: ValueExpr, den: ValueExpr, } | { "expr": "dice-average", dice: Dice, };
