// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dice } from "./Dice";
import type { WeaponKind } from "./WeaponKind";

export type WeaponInstance = { name: string, kind: WeaponKind, damage: Dice, damage_type: string, 
/**
 * Finesse weapons may use DEX instead of STR.
 */
finesse: boolean, two_handed: boolean, 
/**
 * Enhancement bonus from a magic weapon (applies to attack and damage).
 */
magic_bonus: number, proficient: boolean, 
/**
 * 2024 Weapon Mastery property (Vex, Topple, …) the wielder may use.
 */
mastery?: string | null, };
