// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dice } from "./Dice";
import type { WeaponKind } from "./WeaponKind";

export type WeaponView = { name: string, kind: WeaponKind, attack_bonus: number, damage: Dice, damage_bonus: number, damage_type: string, mastery: string | null, };
