//! Bakes the repository's `content/` directory into the binary at compile time,
//! so the packaged app ships self-contained (no external files needed). Emits a
//! generated module with one `include_str!` per content file, tagged by its
//! subdirectory. Zero extra dependencies.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    // content/ lives at the repo root; this crate is at crates/engine.
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let content_root = manifest.join("../../content");

    let kinds = ["classes", "subclasses", "species", "backgrounds", "feats", "spells"];
    let mut entries = String::new();

    for kind in kinds {
        let dir = content_root.join(kind);
        let mut files: Vec<PathBuf> = match fs::read_dir(&dir) {
            Ok(rd) => rd
                .flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
                .collect(),
            Err(_) => Vec::new(),
        };
        files.sort(); // deterministic order
        for path in files {
            // Re-run if any content file changes.
            println!("cargo:rerun-if-changed={}", path.display());
            let abs = fs::canonicalize(&path).unwrap_or(path);
            writeln!(
                entries,
                "    (\"{kind}\", include_str!(r\"{}\")),",
                abs.display()
            )
            .unwrap();
        }
    }
    println!("cargo:rerun-if-changed={}", content_root.display());

    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         pub static EMBEDDED_CONTENT: &[(&str, &str)] = &[\n{entries}];\n"
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("embedded_content.rs");
    fs::write(&out, generated).unwrap();
    let _ = Path::new(&out);
}
