//! Generates the TypeScript bindings the GUI's IPC layer consumes.
//!
//! Run with `cargo test -p rpgman-engine --features ts`. Every engine type that
//! crosses the IPC boundary derives `ts_rs::TS` with `#[ts(export)]`. This test
//! exports them all (and their dependencies) into `<repo>/src/lib/bindings/` —
//! one `.ts` file per type — and writes a barrel `index.ts` re-exporting them,
//! so the frontend can `import type { X } from '$bindings'`.
//!
//! The export directory is set explicitly via [`Config::with_out_dir`] and also
//! via `TS_RS_EXPORT_DIR`, so ts-rs's automatic per-type export (which reads the
//! env var) lands in the same place instead of the default `bindings/` dir.
#![cfg(feature = "ts")]

use std::path::{Path, PathBuf};

use rpgman_engine::build::{PendingChoice, ResolvedFeature};
use rpgman_engine::catalog::Catalog;
use rpgman_engine::computed::ComputedCharacter;
use rpgman_engine::contribution::Contribution;
use rpgman_engine::error::EvalError;
use rpgman_engine::eval::{D20Test, StatBreakdown};
use rpgman_engine::feature::{Feature, NamedOption};
use rpgman_engine::ids::StatId;
use rpgman_engine::resource::ResourceDef;
use rpgman_engine::sheet::CharacterSheet;
use rpgman_engine::value::ValueExpr;
use ts_rs::{Config, TS};

/// Absolute path to `<repo>/src/lib/bindings/`. The crate manifest is
/// `<repo>/crates/engine`, so the bindings dir is two levels up.
fn bindings_dir() -> PathBuf {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/lib/bindings");
    std::fs::create_dir_all(&dir).expect("create src/lib/bindings");
    dir.canonicalize().expect("canonicalize bindings dir")
}

/// Export `T` and every type it transitively references into the configured dir.
macro_rules! export_all {
    ($cfg:expr, $($ty:ty),+ $(,)?) => {
        $( <$ty>::export_all($cfg).expect(concat!("export ", stringify!($ty))); )+
    };
}

#[test]
fn export_typescript_bindings() {
    let out = bindings_dir();

    // Redirect ts-rs's automatic `#[ts(export)]` export (which reads this var via
    // `Config::from_env`) at the frontend bindings dir, so it doesn't also write a
    // stray `crates/engine/bindings/`.
    // SAFETY: set once, early; the explicit exports below don't depend on it.
    unsafe {
        std::env::set_var("TS_RS_EXPORT_DIR", &out);
    }

    let cfg = Config::new().with_out_dir(&out);

    // Roots whose dependency closures together cover every IPC-facing type. The
    // first five are imported directly by src/lib/ipc.ts; the rest drag in the
    // content/build types (Feature, ResourceDef, ...) not reachable from them.
    export_all!(
        &cfg,
        Catalog,
        CharacterSheet,
        ComputedCharacter,
        StatBreakdown,
        StatId,
        D20Test,
        EvalError,
        Contribution,
        ValueExpr,
        Feature,
        NamedOption,
        ResourceDef,
        PendingChoice,
        ResolvedFeature,
    );

    write_barrel(&out);

    // ts-rs's automatic `#[ts(export)]` tests run independently and may have read
    // `Config::from_env` before this test set `TS_RS_EXPORT_DIR`, leaving a stray
    // copy at the crate-default `bindings/`. Remove it so the only output is the
    // frontend dir above.
    let default_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("bindings");
    if default_dir != out {
        let _ = std::fs::remove_dir_all(&default_dir);
    }
}

/// Write `index.ts` re-exporting every generated binding.
fn write_barrel(dir: &Path) {
    let mut names: Vec<String> = std::fs::read_dir(dir)
        .expect("read bindings dir")
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            let stem = name.strip_suffix(".ts")?;
            if stem == "index" {
                None
            } else {
                Some(stem.to_owned())
            }
        })
        .collect();
    names.sort();
    names.dedup();

    let mut barrel =
        String::from("// Generated by `cargo test -p rpgman-engine --features ts`. Do not edit.\n");
    for name in &names {
        barrel.push_str(&format!("export type {{ {name} }} from './{name}';\n"));
    }
    std::fs::write(dir.join("index.ts"), barrel).expect("write index.ts");
}
